### ISSUE TITLE
Malformed json error

### ISSUE THREAD

**Issue by Puyodead1** [DeadlyMC/Skyblock-datapack#7]
Attempting to start a 1.14.4 server but getting this on load
```
[14:49:03] [Server thread/INFO]: Reloading ResourceManager: QuickCarpet, Default, Skyblock-datapack-v1.2.1.zip
[14:49:04] [Server-Worker-2/ERROR]: Couldn't parse data file minecraft:magma_cream from minecraft:recipes/magma_cream.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Expected name at line 3 column 2 path $.type
        at net.minecraft.class_3518.method_15267(class_3518.java:495) ~[intermediary-server.jar:?]
        at net.minecraft.class_3518.method_15276(class_3518.java:533) ~[intermediary-server.jar:?]
        at net.minecraft.class_4309.method_20731(class_4309.java:47) ~[intermediary-server.jar:?]
        at net.minecraft.class_4309.method_18789(class_4309.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_211]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 3 column 2 path $.type
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[server.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505) ~[server.jar:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[server.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[server.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[server.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[server.jar:?]
        at net.minecraft.class_3518.method_15267(class_3518.java:493) ~[intermediary-server.jar:?]
        ... 10 more
```

**Comment by codesource** [comment]
There is a comma too much in `minecraft:recipes/magma_cream.json`
Simply remove it and the error is gone.
